from django.urls import path
from . import views
urlpatterns = [
 path(
 "",
 views.inicio,
 name="inicio",
 ),
 path(
 "cisternas/",
 views.cisterna_listar,
 name="cisterna_listar",
 ),
 path(
 "cisternas/nova/",
 views.cisterna_criar,
 name="cisterna_criar",
 ),
 path(
 "alertas/",
 views.alerta_listar,
 name="alerta_listar",
 ),
 path(
 "alertas/novo/",
 views.alerta_criar,
 name="alerta_criar",
 ),
 path(
 "abastecimentos/",
 views.abastecimento_listar,
 name="abastecimento_listar",
 ),
 path(
 "abastecimentos/novo/",
 views.abastecimento_criar,
 name="abastecimento_criar",
 ),
]
