from django.urls import path
from . import views
urlpatterns = [

path(
"usuarios/",
views.usuario_listar,
name="usuario_listar",
),
path(
"usuarios/novo/",
views.usuario_criar,
name="usuario_criar",
),
path(
"usuarios/<int:pk>/",
views.usuario_detalhar,
name="usuario_detalhar",
),
path(
"usuarios/<int:pk>/editar/",
views.usuario_editar,
name="usuario_editar",
),
path(
"usuarios/<int:pk>/excluir/",
views.usuario_excluir,
name="usuario_excluir",
),
path(
"monitoramentos/",
views.monitoramento_listar,
name="monitoramento_listar",
),
path(
"monitoramentos/novo/",
views.monitoramento_criar,
name="monitoramento_criar",
),

 path(
 "",
 views.inicio,
 name="inicio",
 ),
 path(
 "cisternas/",
 views.cisterna_listar,
 name="cisterna_listar",
 ),
 path(
 "cisternas/nova/",
 views.cisterna_criar,
 name="cisterna_criar",
 ),
 path(
 "alertas/",
 views.alerta_listar,
 name="alerta_listar",
 ),
 path(
 "alertas/novo/",
 views.alerta_criar,
 name="alerta_criar",
 ),
 path(
 "abastecimentos/",
 views.abastecimento_listar,
 name="abastecimento_listar",
 ),
 path(
 "abastecimentos/novo/",
 views.abastecimento_criar,
 name="abastecimento_criar",
 ),
]
