# Generated by Django 6.1 on 2026-09-02 13:03

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cisterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('capacidade', models.FloatField()),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('mensagem', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('dataHora', models.DateTimeField()),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cisternas.cisterna')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField()),
                ('nivelAgua', models.FloatField()),
                ('consumo', models.FloatField()),
                ('situacao', models.CharField(max_length=255)),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='cisternas.cisterna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='cisternas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cisterna',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisternas', to='cisternas.usuario'),
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField()),
                ('quantidadeAgua', models.FloatField()),
                ('tipo', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='cisternas.cisterna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='cisternas.usuario')),
            ],
        ),
    ]
