# Generated by Django 6.1 on 2026-08-15 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cisterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=255)),
                ('capacidade', models.FloatField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('dataHora', models.DateTimeField()),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cisternas.cisterna')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField()),
                ('quantidadeAgua', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='cisternas.cisterna')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField()),
                ('nivelAgua', models.FloatField()),
                ('consumo', models.FloatField()),
                ('situacao', models.CharField(max_length=50)),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='cisternas.cisterna')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodoInicio', models.DateField()),
                ('periodoFim', models.DateField()),
                ('formato', models.CharField(max_length=20)),
                ('dataGeracao', models.DateTimeField()),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='cisternas.cisterna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='cisternas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cisterna',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cisternas', to='cisternas.usuario'),
        ),
    ]
