# Generated by Django 6.1 on 2026-09-21 22:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisternas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cisterna',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='cisterna',
            name='capacidade',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cisterna',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='cisterna',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AlterField(
            model_name='cisterna',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
