# Generated by Django 6.0.3 on 2026-09-22 17:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisternas', '0002_alter_cisterna_options_alter_cisterna_capacidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ('-dataHora', '-id')},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('nome', 'username')},
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='consumo',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='nivelAgua',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
