# Generated by Django 6.1 on 2026-09-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisternas', '0003_alter_alerta_options_alter_abastecimento_options_and_more'),
        ('cisternas', '0003_alter_monitoramento_options_alter_usuario_options_and_more'),
    ]

    operations = [
    ]
